import re
import tomllib
from pathlib import Path


SERVICE_ROOT = Path(__file__).resolve().parents[1]
WORKFLOW_PATH = SERVICE_ROOT / ".github" / "workflows" / "crawl.yml"
COMPOSE_PATH = SERVICE_ROOT / "docker-compose.yml"


def test_dockerfile_installs_from_committed_poetry_lock():
    dockerfile = (SERVICE_ROOT / "Dockerfile").read_text(encoding="utf-8")
    poetry_lock = (SERVICE_ROOT / "poetry.lock").read_text(encoding="utf-8")
    lock_version_match = re.search(r"generated by Poetry ([^\s]+)", poetry_lock)

    assert lock_version_match
    assert f"poetry=={lock_version_match.group(1)}" in dockerfile
    assert "poetry lock" not in dockerfile
    assert "poetry install --only main --no-root" in dockerfile


def test_github_action_builds_crawler_for_arm_server():
    workflow = WORKFLOW_PATH.read_text(encoding="utf-8")

    assert "docker/setup-qemu-action@v3" in workflow
    assert "linux/arm64" in workflow


def test_paddle_ocr_dependencies_are_optional_for_arm_runtime_image():
    pyproject = tomllib.loads((SERVICE_ROOT / "pyproject.toml").read_text(encoding="utf-8"))

    main_dependencies = pyproject["tool"]["poetry"]["dependencies"]
    ocr_group = pyproject["tool"]["poetry"]["group"]["ocr"]
    ocr_dependencies = ocr_group["dependencies"]

    assert ocr_group["optional"] is True
    assert "paddleocr" not in main_dependencies
    assert "paddlepaddle" not in main_dependencies
    assert "paddleocr" in ocr_dependencies
    assert "paddlepaddle" in ocr_dependencies


def test_crawler_writes_media_to_the_shared_container_directory():
    compose = COMPOSE_PATH.read_text(encoding="utf-8")
    workflow = WORKFLOW_PATH.read_text(encoding="utf-8")

    assert "ROOT: /app/public" in compose
    assert (
        "${CRAWLER_MEDIA_HOST_ROOT:-/mnt/kingwangjjang}:/app/public" in compose
    )
    assert 'echo "ROOT=/app/public" >> .env' in workflow


def test_crawler_container_restarts_after_transient_dependency_failure():
    compose = COMPOSE_PATH.read_text(encoding="utf-8")

    assert "restart: unless-stopped" in compose


def test_deploy_recovers_media_before_removing_the_old_container():
    workflow = WORKFLOW_PATH.read_text(encoding="utf-8")

    recovery = 'docker cp "${CRAWLER_CONTAINER_ID}:/app/media/."'
    teardown = "sudo docker-compose down"

    assert recovery in workflow
    assert workflow.index(recovery) < workflow.index(teardown)
