import re
from pathlib import Path


SERVICE_ROOT = Path(__file__).resolve().parents[1]


def test_dockerfile_installs_from_committed_poetry_lock():
    dockerfile = (SERVICE_ROOT / "Dockerfile").read_text(encoding="utf-8")
    poetry_lock = (SERVICE_ROOT / "poetry.lock").read_text(encoding="utf-8")
    lock_version_match = re.search(r"generated by Poetry ([^\s]+)", poetry_lock)

    assert lock_version_match
    assert f"poetry=={lock_version_match.group(1)}" in dockerfile
    assert "poetry lock" not in dockerfile
    assert "poetry install --no-root" in dockerfile
